- hosts: localhost
  roles: 
    - { role: do_vms, name_droplet: "ansiblecontrol-droplet", do_vm_size: "{{ ansible_do_vm_size }}", do_vm_image: "{{ ansible_do_vm_image }}", do_vm_region: "{{ ansible_do_vm_region }}" }

- hosts: temp_inventory_group
  remote_user: root
  become: true
  gather_facts: False
  roles:
    - { role: vm_init }

- hosts: temp_inventory_group
  become: yes
  become_user: appteam
  gather_facts: False
  roles:
    - { role: account_settings }

- hosts: temp_inventory_group
  become: yes
  gather_facts: False
  roles:
    - { role: ansible  }
    - { role: webserver }
    - { role: mysqlserver }
    - { role: redisserver }
    - { role: prepare_ansible_apps }
