- hosts: localhost 
  roles: 
    - { role: do_vms, inventory_group: 'jenkins', name_droplet: "jenkins-droplet", do_vm_size: "{{ ourapp_do_vm_size }}", do_vm_image: "{{ ourapp_do_vm_image}}", do_vm_region: "{{ ourapp_do_vm_region }}" }

- hosts: temp_inventory_group
  remote_user: root
  become: true
  gather_facts: False
  roles:
    - { role: vm_init }

- hosts: temp_inventory_group
  become: yes
  become_user: appteam
  gather_facts: False
  roles:
    - { role: account_settings }

- hosts: temp_inventory_group
  become: yes
  gather_facts: False
  roles:
    - { role: docker }
    - { role: webserver }

- hosts: temp_inventory_group
  remote_user: root
  become: true
  become_user: appteam
  gather_facts: False      
  tasks:
    - name: create jenkins home folder to host Docker Jenkins
      file:
        path: "/home/appteam/jenkins_home"
        owner: "appteam"
        group: "appteam"
        state: directory
        recurse: yes
  
    - name: Run Jenkins container for first time
      docker_container:
        image: jenkinsci/blueocean
        name: mycijenkins
        state: present
        ports:
          - "8080:8080"
          - "50000:50000"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /home/appteam/jenkins_home:/var/jenkins_home
          - /home/appteam:/home
    
    - name: Stop container
      docker_container:
        name: mycijenkins
        state: stopped

    - name: Start container
      docker_container:
        name: mycijenkins
        state: started

    - name: remote inside container to fix permission denied docker
      shell: docker container exec -it -u root mycijenkins bash -c 'addgroup --gid 1001 hostdocker; addgroup jenkins hostdocker'

    - name: Stop container
      docker_container:
        name: mycijenkins
        state: stopped

    - name: Get Temp Admin password for user admin
      shell: cat /home/appteam/jenkins_home/secrets/initialAdminPassword
      register: secretskey
    
    - name: Start container
      docker_container:
        name: mycijenkins
        state: started

    - debug:
        msg: "Key for admin: {{ secretskey.stdout }}"
