- hosts: localhost
  roles: 
    - { role: do_vms, inventory_group: 'ansible_control', name_droplet: "ansiblecontrol-droplet", do_vm_size: "{{ ansible_do_vm_size }}", do_vm_image: "{{ ansible_do_vm_image }}", do_vm_region: "{{ ansible_do_vm_region }}" }

- hosts: temp_inventory_group
  remote_user: root
  become: true
  gather_facts: False
  roles:
    - { role: vm_init }

- hosts: temp_inventory_group
  remote_user: appteam
  become: yes
  become_user: appteam
  gather_facts: False
  roles:
    - { role: account_settings }

- hosts: temp_inventory_group
  become: yes
  gather_facts: False
  roles:
    - { role: ansible  }
    - { role: webserver }
    - { role: mysqlserver }
    - { role: redisserver }
  tasks:
    - name:  copy ssh key to new ansible server for rot user
      copy: src=/home/quangle/.ssh/id_rsa dest=/root/.ssh

    - name:  copy ssh key to new ansible server for rot user
      copy: src=/home/quangle/.ssh/id_rsa.pub dest=/root/.ssh    

- hosts: temp_inventory_group
  become: yes
  become_user: appteam
  gather_facts: False
  roles:
    - { role: prepare_ansible_apps }

- hosts: temp_inventory_group
  remote_user: root
  become: true
  gather_facts: False
  tasks:
    - name: Unlink the symlink of default Nginx file in site-enabled
      file:
        path: "/etc/nginx/sites-enabled/default"
        state: absent

    - name: Remove default Nginx file in site-available
      file:
        path: "/etc/nginx/sites-available/default"
        state: absent

    - name: copy default reverseproxy config file
      copy: src=files/default.conf dest=/etc/nginx/sites-available

    - name: Create symlink to site-enabled
      file: src=/etc/nginx/sites-available/default.conf dest=/etc/nginx/sites-enabled/default state=link

    - name: Nginx restart
      service: name=nginx state=restarted
