- hosts: localhost 
  roles: 
    - { role: do_vms, name_droplet: "ourapp-droplet", do_vm_size: "{{ ourapp_do_vm_size }}", do_vm_image: "{{ ourapp_do_vm_image}}", do_vm_region: "{{ ourapp_do_vm_region }}" }

- hosts: temp_inventory_group
  remote_user: root
  become: true
  gather_facts: False
  roles:
    - { role: vm_init }

- hosts: temp_inventory_group
  become: yes
  become_user: appteam
  gather_facts: False
  roles:
    - { role: account_settings }
    - { role: prepare_our_apps }

- hosts: temp_inventory_group
  become: yes
  gather_facts: False
  roles:
    - { role: docker }
    - { role: webserver }
