- hosts: temp_inventory_group
  remote_user: appteam
  become: true
  become_user: appteam
  gather_facts: False
  tasks:
    #- name: GIT Checkout master branch
    #  git:
    #    repo: 'git@github.com:quanglee/appliedsearch-vm-products.git'
    #    dest: /home/appteam/vm-products-repo
    #    key_file: /home/appteam/.ssh/id_rsa_deploy_vm_products
    #    version: master
    - name: Tear down existing services
      docker_compose:
         project_src: /home/appteam/vm-products-repo
         state: absent

    - name: Create and start services
      docker_compose:
        project_src: /home/appteam/vm-products-repo
      register: output
   
