---
#- debug:
#    msg: " Hello {{ ansible_ssh_host }}"

- name: Ensure jmespath package is install
  pip: executable=pip3 name=jmespath state=present

- name: Ensure jmespath package is install
  pip: name=jmespath state=present

- name: generate deploy key for appliedresearch_ansible repo
  shell: ssh-keygen -b 2048 -t rsa -f /home/appteam/.ssh/id_rsa_deploy_ansible -q -N ""
  args:
    creates: /home/appteam/.ssh/id_rsa_deploy_ansible

- name: generate deploy key for appliedresearch-django-ansible repo
  shell: ssh-keygen -b 2048 -t rsa -f /home/appteam/.ssh/id_rsa_deploy_django_ansible -q -N ""
  args:
    creates: /home/appteam/.ssh/id_rsa_deploy_django_ansible

- name: cat file pub key for ansible repo
  shell: cat /home/appteam/.ssh/id_rsa_deploy_ansible.pub
  register: deploypubkeyansible

- name: cat file pub key for django ansible repo
  shell: cat /home/appteam/.ssh/id_rsa_deploy_django_ansible.pub
  register: deploypubkeydjangoansible

- name: Add GIT deploy key for appteam into ansible repo
  github_deploy_key:
    owner: "quanglee"
    repo: "appliedresearch_ansible"
    name: "appliedresearch-deploy-key"
    key: "{{ deploypubkeyansible.stdout }}"
    read_only: yes
    username: "quanglee"
    password: "{{ vault_github_password }}"
    state: present
    otp: "123456"

- name: Add GIT deploy key for appteam into django ansible repo
  github_deploy_key:
    owner: "quanglee"
    repo: "appliedresearch-django-ansible"
    name: "appliedresearch-django-deploy-key"
    key: "{{ deploypubkeydjangoansible.stdout }}"
    read_only: yes
    username: "quanglee"
    password: "{{ vault_github_password }}"
    state: present
    otp: "123456"

- name: create ansible folder to host GIT Repo
  file:
    path: "/home/appteam/ansible-repo"
    owner: "appteam"
    group: "appteam"
    state: directory
    recurse: yes

- name: create django ansible folder to host GIT Repo
  file:
    path: "/home/appteam/djangoansible-repo"
    owner: "appteam"
    group: "appteam"
    state: directory
    recurse: yes

- name: Git checkout Ansible Repo
  git:
    repo: 'git@github.com:quanglee/appliedresearch_ansible.git'
    dest: /home/appteam/ansible-repo
    key_file: /home/appteam/.ssh/id_rsa_deploy_ansible
    version: master

- name: Git checkout Django Ansible Repo
  git:
    repo: 'git@github.com:quanglee/appliedresearch-django-ansible.git'
    dest: /home/appteam/djangoansible-repo
    key_file: /home/appteam/.ssh/id_rsa_deploy_django_ansible
    version: master

- name: copy vault text to secret place
  copy: src=~/.vault_pass.txt dest=/home/appteam mode=0600

- name:  copy ssh key to new ansible server for appteam user
  copy: src=/home/quangle/.ssh/id_rsa dest=/home/appteam/.ssh

- name:  copy ssh key to new ansible server for appteam user
  copy: src=/home/quangle/.ssh/id_rsa.pub dest=/home/appteam/.ssh
  
- name:  copy ssh key to new ansible server for rot user
  copy: src=/home/quangle/.ssh/id_rsa dest=/home/root/.ssh

- name:  copy ssh key to new ansible server for rot user
  copy: src=/home/quangle/.ssh/id_rsa.pub dest=/home/root/.ssh
