---
# tasks file for account_settings
- name: make direcotry
  file:
    path: "/home/appteam/.ssh"
    state: directory

- name: create empty file
  file:
    path: "/home/appteam/.ssh/authorized_keys"
    state: touch

- name: Update authorized_keys to allow remote to this server with appteam user
  lineinfile:
    path: "/home/appteam/.ssh/authorized_keys"
    line: "{{ ssh_pub_key }}"

- name: Generate SSH Key pair for 'appteam' user
  shell: ssh-keygen -b 2048 -t rsa -f /home/appteam/.ssh/id_rsa -q -N ""
  args:
    creates: /home/appteam/.ssh/id_rsa

- name: change owner to appteam user
  file:
    path: /home/appteam/.ssh
    owner: "appteam"
    group: "appteam"
    recurse: yes

- name: Add GitHub as knownhosts
  shell: ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

