---
- name: Wait for system to become reachable
  wait_for_connection:
    timeout: 300

- name: Initial checks before provisioning server
  command: hostname
  register: myip_address

- name: Install common libraries for Ansible
  apt: name={{item}} state=present update_cache=yes
  with_items:
    - software-properties-common
    - nginx
    - python3-pip
    - python-virtualenv

- name: Update System
  apt: update_cache=yes

- name: Add Repository for Ansible
  apt_repository:
    repo: ppa:ansible/ansible

- name: Install Ansible
  apt: name=ansible state=present update_cache=yes
