---
- name: Install common libraries
  apt: name={{item}} state=present update_cache=yes
  with_items:
    - curl
    - apt-transport-https
    - ca-certificates
    - python3-setuptools
    - software-properties-common
    - python3-pip
    - python-virtualenv

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Update apt and install docker-ce
  apt: update_cache=yes name=docker-ce state=latest

- name: Install Docker Module for Python
  pip:
    name: docker

- name: Install Python docker / docker-compse module
  pip:
    name:
      - docker
      - docker-compose

- name: Pull default Docker image
  docker_image:
    name: "hello-world"
    source: pull

