- name: Initial checks to create {{ name_droplet }} server
  command: hostname

- name: get ssh key info
  digital_ocean_sshkey_info:
    oauth_token: "{{ do_token }}"
  register: ssh_keys

- set_fact:
    pubkey: "{{ item.id }}"
  loop: "{{ ssh_keys.data|json_query(ssh_pubkey) }}"
  vars:
    ssh_pubkey: "[?name=='Ansible SSH Public Key']"

- name: Create Ansible Droplet
  digital_ocean_droplet:
    state: present
    name: "{{ name_droplet }}"
    oauth_token: "{{ do_token }}"
    size: "{{ do_vm_size }}"
    image: "{{ do_vm_image }}"
    region: "{{ do_vm_region }}"
    ssh_keys: ["{{ pubkey }}"]
    wait_timeout: 120
  register: do_droplet

- name: Add {{ do_droplet.data.ip_address }} server to our inventory (temp)
  add_host:
    name: "{{ do_droplet.data.ip_address }}"
    groups: ansible_control_server
    ansible_host: "{{ do_droplet.data.ip_address }}"
    ansible_ssh_host: "{{ do_droplet.data.ip_address }}"
    ansible_user: root
  when: do_droplet is defined
  changed_when: False
